# Métodos Numéricos - Aula 1/2

In [1]:
oi = "oi"
oi

'oi'

In [3]:
import numpy as np

In [4]:
np.array([1, 2])

array([1, 2])

In [14]:
print(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]))
print('')
print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(4, 3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [20]:
a = np.array([[1, 2],[3, 4], [5, 6]])
print(f"número de dimensões: {a.ndim}")
print(f"shape: {a.shape}")
print(f"tamanho: {a.size}")
print(type(a.shape))
print(f"colunas: {a.shape[1]}")

número de dimensões: 2
shape: (3, 2)
tamanho: 6
<class 'tuple'>
colunas: 2


In [29]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 2, 3, 4])
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x ** 2)
print(np.dot(x, y))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[ 1  4  9 16]
30


## Indexação

In [ ]:
xax = np.array([10, 20, 30, 40, 50])
print(xax[1])
print(xax[-1])
print(xax[0:3])
print(xax[:-1])
print(xax[::-1])

20
50
[10 20 30]
[10 20 30 40]
[10 30 50]
[10 40]
[10 50]
[50 40 30 20 10]


In [ ]:
print(xax[::1])
print(xax[::2])
print(xax[::3])
print(xax[::4])
print(xax[::5])

[10 20 30 40 50]
[10 30 50]
[10 40]
[10 50]
[10]


In [56]:
arr = np.array([[1, 2, 3, 4, 5], [10, 20, 30, 40, 50], [7, 8, 9, 10, 11]])
print(arr[2 : 3, 0 : 2])
print("\n", arr[:, 0: 2])
# linha e coluna

[[7 8]]

 [[ 1  2]
 [10 20]
 [ 7  8]]


In [ ]:
np.array([i for i in range(10, 51, 10)])

array([10, 20, 30, 40, 50])