# Aula 20 - Métodos Numéricos
> ## Introdução ao estudo da solução numérica de sistemas lineares

### Métodos

>#### Métodos diretos: 
Em um número finito de passos, chegam à solução exata. (Eliminação de Gauss)

>#### Métodos iterativos: 
"Caminham para a solução", ou seja, em um número infinito de passos estariam lá. (Jacob)

### Sistema triangular inferior

||||||
|:--:|:--:|:--:|:--:|:--:|
|$l_{11}$|0|0|...|0|
|$l_{21}$|$l_{22}$|0|...|0|
|...|...|...|...|...|
|$l_{n1}$|$l_{n2}$|$l_{n3}$|...|$l_{nn}$|

||
|:--:|
|$x_{1}$|
|.|
|.|
|.|
|$x_{n}$|

=====================

||
|:--:|
|$b_{1}$|
|.|
|.|
|.|
|$b_{n}$|

$ l_{11}x_{1} + 0 + 0 + 0 = b_{1} $

$ x_{1} = b_{1} / l_{11} $

$ l_{21}.x_{1} + l_{22}.x_{2} + 0 + 0 = b_{2} $

$ l_{22}.x_{2} = b_{2} - l_{21}.x_{1} $

#### $ x_{2} = \frac{b_{2} - l_{21}.x_{1}} {l_{22}} $

#### $ x_{n} = \frac{b_{n} - l_{n1}x - l_{n2}x_{2} - ... - l_{n n-1}x_{n-1}} {l_{nn}} $

### Substituição Sucessiva

### $ x_{i} = \frac {b_{i} - \sum_{j=1}^{n-1} l_{ij}x_{j}} {l_{ii}} $

### Sistema Triangular Superior

#### $ x_{n} = \frac{b_{n}} {u{n1n}} $

$ u_{n-1, n-1} x_{n-1} + u_{n-1, n} x_{n} = b_{n-1} $

#### $ x_{n-1} = \frac {b_{n-1} - u_{n-1, n} x_{n}} {u_{n-1, n-1}} $

$\sum_{j=i+1}^{n} u_{ik}x_{j}$

### Substituição Retroativa

### $ x_{i} = \frac {b_{i} - \sum_{j=i+1}^{n} u_{ij}x_{j}}{u_{ii}} $

$ i = n, n-1, n-2, ..., 1 $

In [1]:
import numpy as np

In [2]:
def Substituicao_Sucessiva(l, b):
    n = len(b)
    x = np.zeros(n)

    if l.shape[0] != l.shape[1] or l.shape[0] != n:
        return 0

    for i in range(n):
        soma = np.dot(l[i, :i], x[:i])

        if l[i, i] == 0:
            return 0

        x[i] = (b[i] - soma) / l[i][i]

    return x

In [3]:
def Substituicao_Retroativa(l, b):
    n = len(b)
    x = np.zeros(n)

    if l.shape[0] != l.shape[1] or l.shape[0] != n:
        return 0

    for i in range(n -1, -1, -1):
        soma = np.dot(l[i, i+1:], x[i+1:])

        if l[i, i] == 0:
            return 0

        x[i] = (b[i] - soma) / l[i][i]

    return x

In [4]:
l = np.array([[3, 0, 0, 0],
               [2, 5, 0, 0],
               [1, -7, 4, 0],
               [5, 3, -4, 8]])

b = np.array([15, 20, -21, 51])

Substituicao_Sucessiva(l, b)

array([ 5.,  2., -3.,  1.])

In [5]:
m1 = np.array([[3, 0, 0, 0],
               [2, 5, 0, 0],
               [1, -7, 4, 0],
               [5, 3, -4, 8]])

mf = np.array([15, 20, -21, 51])

np.linalg.solve(m1, mf) # array([ 5.,  2., -3.,  1.])

array([ 5.,  2., -3.,  1.])

In [6]:
l = np.array([[4, -1, 3, 2],
               [0, 2, 6, 3],
               [0, 0, 3, 5],
               [0, 0, 0, -2]])

b = np.array([-1, 14, 20, -8])

Substituicao_Retroativa(l, b)

array([-2.,  1.,  0.,  4.])

In [7]:
m1 = np.array([[4, -1, 3, 2],
               [0, 2, 6, 3],
               [0, 0, 3, 5],
               [0, 0, 0, -2]])

mf = np.array([-1, 14, 20, -8])

np.linalg.solve(m1, mf) # array([-2.,  1.,  0.,  4.])

array([-2.,  1.,  0.,  4.])