# Aula 21 - Métodos Numéricos
>## Eliminação de Gauss

Seja o sistema:

$ 2x + y - z = 0 $

$ y + 2z = 0 $

$ -4z = 0 $

|Primeira|Parte||Segunda|
|:-:|:-:|:-:|:-:|
|2|1|-1|0|
|0|1|2|0|
|0|0|-4|0|

Matriz aumentada

Exemplo:
|Primeira||Parte||Segunda|
|:-:|:-:|:-:|:-:|:-:|
|1|1|0|3|4|
|2|1|-1|1|1|
|-3|-1|-1|2|-3|
|-1|2|3|-1|4|

$ -2L_{1} + L_{2} -> L_{2} $

$ -3L_{1} + L_{3} -> L_{3} $

$ 1L_{1} + L_{4} -> L_{4} $

|Primeira||Parte||Segunda|
|:-:|:-:|:-:|:-:|:-:|
|1|1|0|3|4|
|0|-1|-1|-5|-7|
|0|-4|-1|-7|-15|
|0|3|3|2|8|

### $ \frac {-a_{ji}} {a_{ii}} = m_{i} $

$ a_{ii} = pivô $

#### Pivoteamento parcial

Ordenar os elementos das colunas em ordem decrescente de valor absoluto.

In [2]:
import numpy as np

In [23]:
m1 = np.array([[1, 1, 0, 3], 
               [2, 1, -1, 1], 
               [-3, -1, -1, 2], 
               [-1, 2, 3, -1]])
m2 = np.array([4, 1, -3, 4])

def Eliminacao_Gauss(m1, m2):
    mc = m1.copy()
    for i in range(m1.shape[1]):
        



    
    if abs(m1[0,0]) < abs(m1[1,0]):
        m1[0,0] = mc[1,0]
        m1[1,0] = mc[0,0]

    elif abs(m1[0,0]) < abs(m1[2,0]):
        m1[0,0] = mc[2,0]
        m1[2,0] = mc[0,0]

    elif abs(m1[0,0]) < abs(m1[3,0]):
        m1[0,0] = mc[3,0]
        m1[3,0] = mc[0,0]
    print(m1)
    print('\n MC')
    print(mc)

print(abs(m1[2,0]))

3


In [20]:
Eliminacao_Gauss(m1, m2)

[[ 2  1  0  3]
 [ 1  1 -1  1]
 [-3 -1 -1  2]
 [-1  2  3 -1]]

 MC
[[ 1  1  0  3]
 [ 2  1 -1  1]
 [-3 -1 -1  2]
 [-1  2  3 -1]]


In [27]:
print(np.size(m1))
print(m1.shape[1])

16
4
