# Trabalho de Métodos Numéricos

#### Enunciado:

1. Implemente, em Python, uma biblioteca contendo as funções:

    i) Que resolva um sistema triangular superior;

    i) Que resolva um sistema triangular inferior;

    i) Que faça a eliminação de Gauss.

3. Escolha um problema cuja solução envolva resolver um sistema linear de no mínimo 5 incógnitas. Use o jupyter notebook para apresentá-lo, formulá-la e, com a biblioteca do item 1, resolva o problema

#### Questão 2

1. O Problema: Alocação de Recursos na Fábrica "TechMetals"
  
   A fábrica "TechMetals" produz 5 ligas metálicas especiais (Liga A, B, C, D e E). Para produzir essas ligas, a fábrica consome 5 recursos fundamentais: Ferro, Cobre, Alumínio, Energia Elétrica e Horas de Trabalho.

   O gerente precisa saber exatamente quantas toneladas de cada liga foram produzidas no último mês, sabendo o consumo total dos recursos e a "receita" de cada liga.

   Temos os seguintes dados (coeficientes de consumo por tonelada de liga):

   Ferro: A(2), B(1), C(4), D(3), E(1). Total gasto: 140.
   
   Cobre: A(1), B(3), C(2), D(1), E(2). Total gasto: 155.
   
   Alumínio: A(3), B(1), C(1), D(5), E(2). Total gasto: 140.
   
   Energia (MWh): A(1), B(2), C(2), D(2), E(3). Total gasto: 165.
   Trabalho (h): A(2), B(2), C(1), D(1), E(4). Total gasto: 180.

   Objetivo: Encontrar as quantidades $x_1, x_2, x_3, x_4, x_5$ (toneladas das Ligas A, B, C, D, E).

2. Formulação Matemática
  
   Isso gera o sistema linear $Ax = b$:

   $$\begin{cases} 
2x_1 + 1x_2 + 4x_3 + 3x_4 + 1x_5 = 140 \\
1x_1 + 3x_2 + 2x_3 + 1x_4 + 2x_5 = 155 \\
3x_1 + 1x_2 + 1x_3 + 5x_4 + 2x_5 = 140 \\
1x_1 + 2x_2 + 2x_3 + 2x_4 + 3x_5 = 165 \\
2x_1 + 2x_2 + 1x_3 + 1x_4 + 4x_5 = 180 
\end{cases}$$

Matricialmente:

$$A = \begin{bmatrix}
2 & 1 & 4 & 3 & 1 \\
1 & 3 & 2 & 1 & 2 \\
3 & 1 & 1 & 5 & 2 \\
1 & 2 & 2 & 2 & 3 \\
2 & 2 & 1 & 1 & 4
\end{bmatrix}, \quad
b = \begin{bmatrix} 140 \\ 155 \\ 140 \\ 165 \\ 180 \end{bmatrix}$$

3. Solução em Python

Neste código, será utilizada a Eliminação de Gauss com Pivoteamento apenas para transformar a matriz em uma Triangular Superior. Em seguida, será usada a função Substituicao_Retroativa_Superior para finalizar o cálculo.

In [1]:
import numpy as np
import bib_matrizes_triangulares as bib

In [2]:
# Definindo o sistema (A e b)
A_sistema = np.array([
    [2, 1, 4, 3, 1],
    [1, 3, 2, 1, 2],
    [3, 1, 1, 5, 2],
    [1, 2, 2, 2, 3],
    [2, 2, 1, 1, 4]
], dtype=float)

b_sistema = np.array([140, 155, 140, 165, 180], dtype=float)

print("--- Matriz Original ---")
print(A_sistema)

# PASSO 1: Triangularizar a matriz (Lógica de Gauss com Pivoteamento)
U, b_modificado = bib.gauss_triangulacao_parcial(A_sistema, b_sistema)

print("\n--- Matriz Triangular Superior (Após Gauss) ---")
print(np.round(U, 2))

# PASSO 2: Resolver x (Usando SUA função de Substituição Retroativa)
# Note que passamos a matriz U e o b modificado
resultado_final = bib.Substituicao_Retroativa_Superior(U, b_modificado)

print("\n--- Solução Final (Quantidades produzidas) ---")
ligas = ['A', 'B', 'C', 'D', 'E']
for liga, qtd in zip(ligas, resultado_final):
    print(f"Liga {liga}: {qtd:.2f} toneladas")

--- Matriz Original ---
[[2. 1. 4. 3. 1.]
 [1. 3. 2. 1. 2.]
 [3. 1. 1. 5. 2.]
 [1. 2. 2. 2. 3.]
 [2. 2. 1. 1. 4.]]

--- Matriz Triangular Superior (Após Gauss) ---
[[ 3.    1.    1.    5.    2.  ]
 [ 0.    2.67  1.67 -0.67  1.33]
 [ 0.    0.    3.12 -0.25 -0.5 ]
 [ 0.    0.    0.   -2.04  1.92]
 [ 0.    0.    0.    0.    2.35]]

--- Solução Final (Quantidades produzidas) ---
Liga A: 10.00 toneladas
Liga B: 20.00 toneladas
Liga C: 15.00 toneladas
Liga D: 5.00 toneladas
Liga E: 25.00 toneladas
